build_image:
  script:
    - docker login -u="$GIT_USER" -p="$GIT_PASS"
    - "docker build -t d-dashboard:build ."
    - "docker tag d-dashboard:build jc6482/d-dashboard:latest_dev"
    - "docker push jc6482/d-dashboard:latest_dev"
    - "docker rmi -f d-dashboard:build jc6482/d-dashboard:latest_dev || true"
    - docker logout

sonar_scan:
  script:
    - /opt/sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=D-DASH -Dsonar.sources=. -Dsonar.host.url=http://10.64.0.5:30900 -Dsonar.login=$SONAR_TOKEN

kube_deploy:
  script:
    - /usr/bin/kubectl apply -f deployment.yaml
