apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d-dashboard
  namespace: tos
  labels:
    run: d-dashboard
    namespace: tos
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: d-dashboard
        namespace: tos
    spec:
      volumes:
      - name: d-dashboard-secrets
        secret:
          secretName: d-dashboard-secret-mount
      containers:
      - name: d-dashboard
        image: jc6482/d-dashboard:latest_dev
        env:
          - name: RAILS_ENVIRONMENT
            value: production
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: "/opt/D-Dashboard/.env"
          subPath: ".env"
          readOnly: true
          name: d-dashboard-secrets
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: d-dashboard
  namespace: tos
spec:
  selector:
    run: d-dashboard
  ports:
    - name: ui-port
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
